{
  "formatVersion": "1.1",
  "component": {
    "group": "com.okay.smartteacher",
    "module": "dev",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6u7djfrezzdnhinlu4tdou5lze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dev-0.0.1.jar",
          "url": "dev-0.0.1.jar",
          "size": 5086,
          "sha512": "d3a9004aab6ae493ceac0b13f1bde5d87ca23dfe113a2f431b41f5afc70038dec1249c20543d90e9833f1287d19f73354aa530e7ed29438927191e544f90b042",
          "sha256": "58852b23b89384cfc9224d273bd980aed343399de7cf538677b9746341a729ac",
          "sha1": "3593bfe278788f0edda492dbe550dbd06a77416e",
          "md5": "c674b2d498773c87cad3cf86fb5898e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dev-0.0.1.jar",
          "url": "dev-0.0.1.jar",
          "size": 5086,
          "sha512": "d3a9004aab6ae493ceac0b13f1bde5d87ca23dfe113a2f431b41f5afc70038dec1249c20543d90e9833f1287d19f73354aa530e7ed29438927191e544f90b042",
          "sha256": "58852b23b89384cfc9224d273bd980aed343399de7cf538677b9746341a729ac",
          "sha1": "3593bfe278788f0edda492dbe550dbd06a77416e",
          "md5": "c674b2d498773c87cad3cf86fb5898e2"
        }
      ]
    }
  ]
}
