{
  "formatVersion": "1.1",
  "component": {
    "group": "com.okay.smartteacher",
    "module": "dev",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ifgjktngm5cpjidgfozpqszjpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dev-0.0.2.jar",
          "url": "dev-0.0.2.jar",
          "size": 6700,
          "sha512": "1c68e0690bf433cab85243488f188f3d42550362822c984bc684ec8ef09a1c41f763ecd3a7ebc7c01e515ba532c7c4a0fa787ba0e027b6ab40e0d70ee59cc9ca",
          "sha256": "8cd6b969f49a852325891bfa04aac2d772116cc6ac1de02b3e01b66fa82cd509",
          "sha1": "b309b821ed79afbfde18cf426d1dfa570c8d99cd",
          "md5": "2a74c2afad5e05ce1ae716496c67e1af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dev-0.0.2.jar",
          "url": "dev-0.0.2.jar",
          "size": 6700,
          "sha512": "1c68e0690bf433cab85243488f188f3d42550362822c984bc684ec8ef09a1c41f763ecd3a7ebc7c01e515ba532c7c4a0fa787ba0e027b6ab40e0d70ee59cc9ca",
          "sha256": "8cd6b969f49a852325891bfa04aac2d772116cc6ac1de02b3e01b66fa82cd509",
          "sha1": "b309b821ed79afbfde18cf426d1dfa570c8d99cd",
          "md5": "2a74c2afad5e05ce1ae716496c67e1af"
        }
      ]
    }
  ]
}
